data: 'shrec_skeleton'
data_param:
  train_data_param:
    data_path: ../data_files/SHREC/train_skeleton.pkl
    label_path: ../data_files/SHREC/train_label_28.pkl
    random_choose: True
    center_choose: False
    window_size: 40
    final_size: 40
    num_skip_frame:
    decouple_spatial: False
  val_data_param:
    data_path: ../data_files/SHREC/val_skeleton.pkl
    label_path: ../data_files/SHREC/val_label_28.pkl
    random_choose: False
    center_choose: True
    window_size: 40
    final_size: 40
    num_skip_frame:
    decouple_spatial: False

# model
model: 'stst'
class_num: 28
model_param:
  num_point: 22
  num_frame: 40
  attention_head_S: 3
  attention_head_T: 2
  num_person: 1
  glo_reg_s: True
  dropout: 0
  attentiondrop: 0
  dropout2d: 0
  parallel: True
  S_atten: 'free'
  T_atten: 'context_new'
  directed: True
  TCN: True
  config: [ [64, 64, 16, 1],[64, 128, 32, 1],
            [128, 256, 64, 1], [256, 256, 64, 1],
  ]
  use_SSL: False
  SSL_option: {'PC': False, 'PS': False, 'PT': False, 'RT': False, 'CL': False}
  SSL_weight: {'PC': 0.1, 'PS': 0.1, 'PT': 0.1, 'RT': 0.1, 'CL': 0.1}
  mask_divide: [0.8, 0.1, 0.1]
  var: 0.5
  num_seg: 3

#  config: [ [64, 64, 16, 1], [64, 64, 16, 1],
#            [64, 128, 32, 1], [128, 128, 32, 1],
#            [128, 256, 64, 1], [256, 256, 64, 1],
#            [256, 256, 64, 1], [256, 256, 64, 1],
#  ]


train: 'classify'
mode: 'test'
loss: 'cross_entropy'
batch_size: 64
worker: 32
pin_memory: False
num_epoch_per_save: 30
model_saved_name: './work_dir/shrec28/stst_toy'
last_model: './work_dir/shrec/stst_toy_28-latest.state'
pre_trained_model:
ignore_weights: []
label_smoothing_num: 0
mix_up_num: 0
device_id: []
cuda_visible_device: ''
debug: False

# lr
lr_scheduler: 'reduce_by_epoch'
lr_param:
  step: [60, 90, 120]
  gamma: 0.1
#  lr_patience: 20
#  lr_threshold: 0.0001
#  lr_delay: 10
warm_up_epoch: 5
max_epoch: 150
lr: 0.1
wd: 0.0005
lr_decay_ratio: 0.1
lr_multi_keys: []

# optimizer
optimizer: 'sgd_nev'
freeze_keys: []

